# https://github.com/actions/labeler
monorepo:
    - changed-files:
          - any-glob-to-any-file:
                - '!plugins/**'
                - '!themes/**'

plugin:
    - changed-files:
          - any-glob-to-any-file: 'plugins/**'

theme:
    - changed-files:
          - any-glob-to-any-file: 'themes/**'

themes/child-theme-belleville-terminal:
    - changed-files:
          - any-glob-to-any-file: 'themes/design-system-wordpress-child-theme-belleville-terminal/**'

plugins/bcgov-wordpress-blocks:
    - changed-files:
          - any-glob-to-any-file: 'plugins/bcgov-wordpress-blocks/**'

themes/child-theme-ticorp:
    - changed-files:
          - any-glob-to-any-file: 'themes/design-system-wordpress-child-theme-ticorp/**'
