<?php
/**
 * Plugin Name: Design System Plugin
 * Plugin URI: https://github.com/bcgov/design-system-wordpress-plugin
 * Author: govwordpress@gov.bc.ca
 * Author URI: https://apps.itsm.gov.bc.ca/jira/browse/ENG-138
 * Description: WordPress Design System plugin is a plugin that adds custom functionality to your WordPress site.
 * Requires at least: 6.4.4
 * Tested up to: 6.5
 * Requires PHP: 7.4
 * Version: 2.5.0
 * License: Apache License Version 2.0
 * License URI: LICENSE
 * Text Domain: design-system-wordpress-plugin
 * Tags:
 *
 * @package DesignSystemPlugin
 */

/**
 * Loads the autoloader.
 */
if ( ! class_exists( 'Bcgov\\DesignSystemPlugin\\NotificationBanner' ) ) {
    $local_composer  = __DIR__ . '/vendor/autoload.php';
    $server_composer = __DIR__ . '/../../../../vendor/autoload.php';
    if ( file_exists( $local_composer ) || file_exists( $server_composer ) ) {
        if ( file_exists( $server_composer ) ) {
            require_once $server_composer;
        }
        if ( ! class_exists( 'Bcgov\\DesignSystemPlugin\\NotificationBanner' ) ) {
            require_once $local_composer;
        }
    }
}

/**
 * The function design_system_register_blocks registers block types from metadata in block.json files
 * found in subdirectories of the Blocks/build folder.
 */
function design_system_register_blocks() {
    // Define the path to the build directory.
    $build_dir = plugin_dir_path( __FILE__ ) . 'Blocks/build/';

    // Use glob to find all block.json files in the subdirectories of the build folder.
    $block_files = glob( $build_dir . '*/block.json' );
    // Loop through each block.json file.
    foreach ( $block_files as $block_file ) {
        // Register the block type from the metadata in block.json.
        register_block_type_from_metadata( $block_file );
    }
}
// Hook the function into the 'init' action.
add_action( 'init', 'design_system_register_blocks' );


/**
 * Enqueues the auto-anchor JavaScript file for the block editor if the feature is enabled.
 *
 * This function loads the auto-anchor script and its dependencies in the block editor,
 * but only if the auto-anchor feature is enabled in settings and the script file exists.
 */
function enqueue_auto_anchor_script() {
    // Check if the feature is enabled.
    if ( get_option( 'dswp_auto_anchor_enabled', '1' ) !== '1' ) {
        return;
    }

    $script_path = plugin_dir_path( __FILE__ ) . 'dist/auto-anchor.js';
    $script_url  = plugin_dir_url( __FILE__ ) . 'dist/auto-anchor.js';

    // This file is automatically generated and includes all necessary dependencies.
    $asset_file = include plugin_dir_path( __FILE__ ) . 'dist/auto-anchor.asset.php';

    if ( file_exists( $script_path ) ) {
        wp_enqueue_script(
            'auto-anchor',
            $script_url,
            $asset_file['dependencies'],
            $asset_file['version'],
            true
        );
    }
}
add_action( 'enqueue_block_editor_assets', 'enqueue_auto_anchor_script' );


/**
 * Adds a new block category for Design System blocks
 *
 * This function adds a new category to the WordPress block editor (Gutenberg)
 * that will contain all Design System blocks. The category is added to the
 * beginning of the categories list using array_unshift.
 *
 * @since 1.0.0
 *
 * @param array $categories Array of block categories.
 * @return array   Modified array of block categories.
 */
function dswp_add_new_block_category( $categories ) {
    array_unshift(
        $categories,
        array(
            'slug'  => 'design_system',
            'title' => 'Design System',
        )
    );

    return $categories;
}
add_filter( 'block_categories_all', 'dswp_add_new_block_category', 10, 2 );


/**
 * Enqueues the in-page navigation scripts and styles.
 *
 * This function checks if the current context is a page or post
 * and verifies if the in-page navigation toggle is enabled for that
 * specific page or post. If both conditions are satisfied, it loads
 * the necessary JavaScript and CSS files for the in-page navigation feature.
 *
 * The JavaScript file (in-page-nav.js) is responsible for creating
 * and managing the navigation menu, while the CSS file (in-page-nav.css)
 * contains the styling for the navigation menu.
 *
 * @since 1.0.0
 * @uses is_page()
 * @uses get_post_meta()
 * @uses wp_enqueue_script()
 * @uses wp_enqueue_style()
 * @uses plugin_dir_url()
 */
function enqueue_in_page_nav() {
    // This file is automatically generated and includes all necessary dependencies.
    $asset_file = include plugin_dir_path( __FILE__ ) . 'dist/in-page-nav.asset.php';

    if ( is_page() ) {
        $show_nav = get_post_meta( get_the_ID(), 'show_inpage_nav', true );
        if ( $show_nav ) {
            // Frontend functionality.
            wp_enqueue_script(
                'in-page-nav',
                plugin_dir_url( __FILE__ ) . 'dist/in-page-nav.js',
                $asset_file['dependencies'],
                $asset_file['version'],
                true
            );// Frontend styles.
            wp_enqueue_style(
                'in-page-nav-styles',
                plugin_dir_url( __FILE__ ) . 'dist/in-page-nav.css',
                array(),
                $asset_file['version'],
            );
        }
    }
}
add_action( 'wp_enqueue_scripts', 'enqueue_in_page_nav' );

/**
 * Registers the meta field for the in-page navigation toggle.
 *
 * This function registers a custom meta field 'show_inpage_nav' for pages
 * that controls whether the in-page navigation should be displayed.
 * The meta field is:
 * - Accessible through the REST API (show_in_rest)
 * - Single value per page (single)
 * - Boolean type (true/false)
 * - Defaults to false (navigation disabled)
 *
 * This meta registration is necessary for the block editor to
 * interact with the toggle setting through the REST API.
 *
 * @since 1.0.0
 * @uses register_post_meta()
 */
function register_inpage_nav_meta() {
    register_post_meta(
        'page',
        'show_inpage_nav',
        array(
			'show_in_rest' => true,
			'single'       => true,
			'type'         => 'boolean',
			'default'      => false,
        )
    );
}
add_action( 'init', 'register_inpage_nav_meta' );

/**
 * Enqueues scripts for the in-page navigation editor interface.
 *
 * This function loads the JavaScript required for the in-page navigation
 * toggle control in the block editor. It includes necessary WordPress
 * dependencies for:
 * - Plugin functionality (wp-plugins)
 * - Editor modifications (wp-edit-post)
 * - React elements (wp-element)
 * - WordPress UI components (wp-components)
 * - Data management (wp-data)
 * - Internationalization (wp-i18n)
 *
 * The script is only loaded in the block editor context and handles
 * the toggle interface for enabling/disabling in-page navigation.
 *
 * @since 1.0.0
 * @uses wp_enqueue_script()
 * @uses plugin_dir_url()
 */
function enqueue_editor_scripts() {

	// This file is automatically generated and includes all necessary dependencies.
	$asset_file = include plugin_dir_path( __FILE__ ) . 'dist/in-page-nav-page-settings.asset.php';

    wp_enqueue_script(
        'inpage-nav-editor',
        plugin_dir_url( __FILE__ ) . 'dist/in-page-nav-page-settings.js',
        $asset_file['dependencies'],
        $asset_file['version'],
        true
    );

    wp_enqueue_style(
        'in-page-nav-styles',
        plugin_dir_url( __FILE__ ) . 'dist/in-page-nav.css',
        array(),
        $asset_file['version'],
    );
}
add_action( 'enqueue_block_editor_assets', 'enqueue_editor_scripts' );


use Bcgov\DesignSystemPlugin\{
    DesignSystemSettings,
    NotificationBanner,
    ContentSecurityPolicy,
    SkipNavigation,
};

use Bcgov\DesignSystemPlugin\Enqueue\{
    Style,
    Script
};

use Bcgov\DesignSystemPlugin\AutoAnchor\Settings as AutoAnchorSettings;



// Initialize the main Design System settings page.
$design_system_settings = new DesignSystemSettings();
$design_system_settings->init();

// Initialize the custom banner class.
$notification_banner = new NotificationBanner();
$notification_banner->init();

// Initialize the content security policy class.
$content_security_policy = new ContentSecurityPolicy();
$content_security_policy->init();


// Initialize the content security policy class.
$skip_navigation = new SkipNavigation();
$skip_navigation->init();

// Initialize the enqueueing styles class.
$enque_styles = new Style();
$enque_styles->init();

// Initialize the enqueueing scripts class.
$enqueue_scripts = new Script();
$enqueue_scripts->init();

// Initialize the AutoAnchorSettings.
$auto_anchor_settings = new AutoAnchorSettings();
$auto_anchor_settings->init();
