<?php
/**
 * Plugin Name: Design System Plugin
 * Plugin URI: https://github.com/bcgov/design-system-wordpress-plugin
 * Author: govwordpress@gov.bc.ca
 * Author URI: https://apps.itsm.gov.bc.ca/jira/browse/ENG-138
 * Description: WordPress Design System plugin is a plugin that adds custom functionality to your WordPress site.
 * Requires at least: 6.4.4
 * Tested up to: 6.5
 * Requires PHP: 7.4
 * Version: 2.4.0
 * License: Apache License Version 2.0
 * License URI: LICENSE
 * Text Domain: design-system-wordpress-plugin
 * Tags:
 *
 * @package DesignSystemPlugin
 */

/**
 * Loads the autoloader.
 */
if ( ! class_exists( 'Bcgov\\DesignSystemPlugin\\NotificationBanner' ) ) {
    $local_composer  = __DIR__ . '/vendor/autoload.php';
    $server_composer = __DIR__ . '/../../../../vendor/autoload.php';
    if ( file_exists( $local_composer ) || file_exists( $server_composer ) ) {
        if ( file_exists( $server_composer ) ) {
            require_once $server_composer;
        }
        if ( ! class_exists( 'Bcgov\\DesignSystemPlugin\\NotificationBanner' ) ) {
            require_once $local_composer;
        }
    }
}

/**
 * The function design_system_register_blocks registers block types from metadata in block.json files
 * found in subdirectories of the Blocks/build folder.
 */
function design_system_register_blocks() {
    // Define the path to the build directory.
    $build_dir = plugin_dir_path( __FILE__ ) . 'Blocks/build/';

    // Use glob to find all block.json files in the subdirectories of the build folder.
    $block_files = glob( $build_dir . '*/block.json' );
    // Loop through each block.json file.
    foreach ( $block_files as $block_file ) {
        // Register the block type from the metadata in block.json.
        register_block_type_from_metadata( $block_file );
    }
}
// Hook the function into the 'init' action.
add_action( 'init', 'design_system_register_blocks' );


/**
 * Enqueues the auto-anchor JavaScript file for the block editor if the feature is enabled.
 *
 * This function loads the auto-anchor script and its dependencies in the block editor,
 * but only if the auto-anchor feature is enabled in settings and the script file exists.
 */
function enqueue_auto_anchor_script() {
    // Check if the feature is enabled.
    if ( get_option( 'dswp_auto_anchor_enabled', '1' ) !== '1' ) {
        return;
    }

    $script_path = plugin_dir_path( __FILE__ ) . 'dist/auto-anchor.js';
    $script_url  = plugin_dir_url( __FILE__ ) . 'dist/auto-anchor.js';

    // This file is automatically generated and includes all necessary dependencies.
    $asset_file = include plugin_dir_path( __FILE__ ) . 'dist/auto-anchor.asset.php';

    if ( file_exists( $script_path ) ) {
        wp_enqueue_script(
            'auto-anchor',
            $script_url,
            $asset_file['dependencies'],
            $asset_file['version'],
            true
        );
    }
}
add_action( 'enqueue_block_editor_assets', 'enqueue_auto_anchor_script' );


// Adding a new (custom) block category and show that category at the top
function dswp_add_new_block_category( $categories, $post ) {
	
	array_unshift( $categories, array(
		'slug'	=> 'design_system',
		'title' => 'Design System'
	) );

	return $categories;
}
add_filter( 'block_categories_all', 'dswp_add_new_block_category', 10, 2);



function enqueue_in_page_nav() {
    if (is_page()) {
        $show_nav = get_post_meta(get_the_ID(), 'show_inpage_nav', true);
        
        if ($show_nav) {
            wp_enqueue_script(
                'in-page-nav',
                plugin_dir_url(__FILE__) . 'dist/in-page-nav.js',
                array(),
                '1.0.0',
                true
            );
            wp_enqueue_style(
                'in-page-nav-styles',
                plugin_dir_url(__FILE__) . 'dist/style-in-page-nav.css'
            );
        }
    }
}
add_action('wp_enqueue_scripts', 'enqueue_in_page_nav');

// This is necessary - it registers the meta field for the toggle
function register_inpage_nav_meta() {
    register_post_meta('page', 'show_inpage_nav', array(
        'show_in_rest' => true,
        'single' => true,
        'type' => 'boolean',
        'default' => false,
    ));
}
add_action('init', 'register_inpage_nav_meta');

use Bcgov\DesignSystemPlugin\{
    DesignSystemSettings,
    NotificationBanner,
    ContentSecurityPolicy,
    SkipNavigation,
};

use Bcgov\DesignSystemPlugin\Enqueue\{
    Style,
    Script
};

use Bcgov\DesignSystemPlugin\AutoAnchor\Settings as AutoAnchorSettings;



// Initialize the main Design System settings page.
$design_system_settings = new DesignSystemSettings();
$design_system_settings->init();

// Initialize the custom banner class.
$notification_banner = new NotificationBanner();
$notification_banner->init();

// Initialize the content security policy class.
$content_security_policy = new ContentSecurityPolicy();
$content_security_policy->init();


// Initialize the content security policy class.
$skip_navigation = new SkipNavigation();
$skip_navigation->init();

// Initialize the enqueueing styles class.
$enque_styles = new Style();
$enque_styles->init();

// Initialize the enqueueing scripts class.
$enqueue_scripts = new Script();
$enqueue_scripts->init();

// Initialize the AutoAnchorSettings.
$auto_anchor_settings = new AutoAnchorSettings();
$auto_anchor_settings->init();



function enqueue_editor_scripts() {
    wp_enqueue_script(
        'inpage-nav-editor',
        plugin_dir_url(__FILE__) . 'dist/in-page-nav-editor.js',
        array(
            'wp-plugins',
            'wp-edit-post',
            'wp-element',
            'wp-components',
            'wp-data',
            'wp-i18n'
        ),
        '1.0.0',
        true
    );
}
add_action('enqueue_block_editor_assets', 'enqueue_editor_scripts');
