name: Pull request checks

on:
    pull_request:

# Avoid duplicate runs on force-pushes
concurrency:
    group: pr-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    labeler:
        name: Add labels
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/labeler@v6
              with:
                  sync-labels: true

    lint:
        name: Lint monorepo and test affected projects
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install pnpm 
              uses: pnpm/action-setup@v4
              with:
                  version: 10
                  cache: true

            - name: Setup Node.js 24
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Install Composer dependencies
              run: composer i

            - name: Run php lint
              run: pnpm run lint-php

            - name: Run js lint
              run: pnpm run lint-js

            - name: Run css lint
              run: pnpm run lint-css

            - name: Run md lint
              run: pnpm run lint-md

            - name: Run package.json lint
              run: pnpm run lint-pkg-json

            - name: Install Playwright dependencies
              run: npx playwright install --with-deps

            - name: Build
              run: npx nx affected --base="origin/${{ github.base_ref }}" -t build

            - name: Run e2e tests
              run: npx nx affected --base="origin/${{ github.base_ref }}" -t test-e2e

            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: artifacts/test-results/
                  retention-days: 30

            - name: Run screenshot updates
              run: npx nx affected --base="origin/${{ github.base_ref }}" -t test-screenshot

            - name: Run PHP integration tests
              run: npx nx affected --base="origin/${{ github.base_ref }}" -t test-integration

            # Todo: Determine how to allow bot commits without retriggering default CodeQL check.
            # - name: Commit and push updates
            #   uses: stefanzweifel/git-auto-commit-action@v7.1.0
            #   with:
            #     commit_message: 'Update e2e snapshots (committed automatically via Visual Regression workflow) [skip ci]'
