name: Release Subproject and Update packages.json
on:
  push:
    tags:
      - '**/v*'

concurrency: 
  group: composer-repo-update
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm 
        uses: pnpm/action-setup@v4
        with:
            version: 10
            cache: true

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
            node-version: 24
            cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Parse Tag
        id: vars
        shell: bash
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "name=${TAG%/*}" >> $GITHUB_OUTPUT
          echo "version=${TAG##*/}" >> $GITHUB_OUTPUT
          echo "project_path=$(npx nx show project bcgov-wordpress-blocks --json | jq -r .root)" >> $GITHUB_OUTPUT

      - name: Install Composer dependencies
        run: npx nx run ${{ steps.vars.outputs.name }}:composer-install

      - name: Nx Build
        run: npx nx run ${{ steps.vars.outputs.name }}:build

      - name: Zip Artifacts
        working-directory: ${{ steps.vars.outputs.project_path }}
        run: |
            git add -f dist/
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "chore: commit build files"
            git archive --output=dist.zip ${{ steps.vars.outputs.tag }} ./

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ steps.vars.outputs.project_path }}/dist.zip
          tag_name: ${{ steps.vars.outputs.tag }}

      - name: Update packages.json
        env:
          REPOSITORY: ${{ github.repository }}
          TAG: ${{ steps.vars.outputs.tag }}
          VERSION: ${{ steps.vars.outputs.version }}
          PROJECT_PATH: ${{ steps.vars.outputs.project_path }}
        run: |
          curl -sL https://${{ github.repository_owner }}.github.io/wordpress-monorepo/packages.json -o packages.json || echo '{"packages":{}}' > packages.json

          mkdir public
          touch public/packages.json

          php .github/scripts/update-packages.php
          
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
